spring:
  threads:
    virtual:
      enabled: true

ollama:
  url: ${OLLAMA_URL:http://localhost:11434}

documents:
  path: ${DOCUMENTS_PATH:src/main/resources/documents}
transcriptions:
  path: ${TRANSCRIPTIONS_PATH:src/main/resources/transcriptions}

langchain4j:
  open-ai:
    chat-model:
      api-key: ${OPENAI_API_KEY}
      model-name: ${OPENAI_MODEL_NAME:gpt-4-turbo}
      temperature: ${OPENAI_TEMPERATURE:1.0}